### ISSUE TITLE
can you make tutorial how to make it work on emulator??

### ISSUE THREAD

**Issue by Evil-Pro** [dragonjumeog/DragonFist#1]
can you make tutorial for how to make it work on emulator?

**Comment by esby97** [comment]
It is not different from using real smartphone.
But if your APK file don't have x86 library, you can't use emulator for analysis.

If your APK have x86 library, then
1. Select Target Library Architecture "x86".
2. open cmd and run frida-server-XXX-x86.
3. run your target game.
