### ISSUE TITLE
Hooking

### ISSUE THREAD

**Issue by daeinlee** [dragonjumeog/DragonFist#2]
안녕하세요. 우선 유용한 프로그램 만들어 주셔서 감사합니다.
툴을 테스트하던 중 궁금한 부분이 있어서 문의드립니다. 

1. Frida-sever 12.7.12로 함수 Hook 기능 이용 시 Hooking되는 함수가 없습니다. 다만, Report의 함수 후킹 가능성에는 안전이라고 나옵니다.
   안전해서  Hooking이 되는 함수가 없는 것인지 궁금합니다. (테스트는 카운터사이드라는 게임으로 했습니다)

- Pixel Xl 안드로이드7.0 디바이스로 테스트했습니다.

2. 최신 버전의  Frida-sever에서는 에러가 발생합니다. hook.js의 액세스에 대한 경로가 거부되었다고 나오는데 관리자로 실행해도 동일한 문제가 발생합니다. 

- > 이제 모두 해결했습니다~! 감사합니다!

**Comment by ch4rli3kop** [comment]
@daeinlee 레포지토리 관리를 너무 안 했었네요 ㅠㅠ 도움을 못 드렸어서 죄송합니다 ㅜㅜ 앞으로는 신경써서 관리하도록 하겠습니다!

**Comment by daeinlee** [comment]
@ch4rli3kop  
잘못된 부분이 실제로 있엇던 것이 아니라, 시연 영상이 에뮬레이터라서 녹스로 확인을 해서 발생한 문제들이었습니다.
혹시나 다른 분들도 착각할 수 있으니, 안내해주면 좋을 것 같습니다.

**Comment by ch4rli3kop** [comment]
@daeinlee 아하 ㅠ 저희가 LD Player를 대부분 사용했던터라 다른 에뮬레이터에 대한 테스트가 부족했습니다 ㅠㅠ 좋은 정보 감사드립니다!
