### ISSUE TITLE
Hooking not working, tried multiple Frida versions. 

### ISSUE THREAD

**Issue by AWO52PZ44IKE7FDR79DV2999BCZK19R0IFLDGHF** [dragonjumeog/DragonFist#4]
This tool is so great 😃 But I am having an issue using the hooking tool because It does not do anything for me.

**I make my "Hooking List" and then I select "Run"**

![List](https://i.ibb.co/7jw03nc/frida4.png)

**I select "Run" again on this next page to hook my Frida:**

![List](https://i.ibb.co/FVRkCjz/frida2.jpg)

**But nothing happens at all, no PID and no ARCH found. It just doesn't do anything..:**

![List](https://i.ibb.co/JpBD3PQ/okok.png)

**I know the Frida works because if I close my app and I try to click run I get this error:**

 ![List](https://i.ibb.co/JzSmjg9/closed.png)

**I also double checked to make sure my Frida is working just fine on ADB:**

 ![List](https://i.ibb.co/vYwLG4p/frida1.png)

**Now I click the "Back" button to go back to hooks page:**

 ![List](https://i.ibb.co/84yGs3t/back.png)

**And I get this error when I try to go back, not sure if this is related to the problem:**

 ![List](https://i.ibb.co/qjcXcbv/frida3.png)

I have tried so many different Frida versions on my PC and on my Android over last **4** hours trying to fix this:

- 14.1.3
- 14.1.2
- 14.1.1
- 14.1.0
- 12.7.21
- 12.7.20
- 12.7.19
- 12.7.18
- 12.7.17

I am on Android 8.1 Oreo, Pixel 2XL. Nothing I do seems to be working 😞

Any tips for me is so much appreciated!

**Comment by esby97** [comment]
Hello @AWO52PZ44IKE7FDR79DV2999BCZK19R0IFLDGHF ! Thanks for using our program :P

I think you didn't run the game on the phone before using DragonFist tool. The error occurs because program can not find [PACKAGE_NAME] process from your phone.

If Frida connection is successful, PID and Arch will appear.
